### ISSUE TITLE
Tekst buiten container

### ISSUE THREAD

**Issue by elina2022** [amirdev98/connect-your-tribe-profile-card#2]
![image](https://user-images.githubusercontent.com/112861148/218059232-0119945a-94fe-4072-9b5e-422f6bebc15d.png)

Alle content staat in de container in het midden behalve je naam. Is dit intenioneel? Zo niet, dan kan je hier even naar kijken

**Comment by amirnapoletano** [comment]
Dankjewel Elina, ik heb je issue verwerkt
