### ISSUE TITLE
Verkeerd opgeschreven

### ISSUE THREAD

**Issue by ChrisvanderHorst0308** [amirdev98/connect-your-tribe-profile-card#4]
hi Amir,

bij regel 9 in je html :     <img src="<= member.avatar%>" alt="Avatar van <%= member.name%>"

hierbij mist het procent teken:

ik heb voor je tussen ! ! gezet

    <img src="< ! % ! = member.avatar%>" alt="Avatar van <%= member.name%>"

**Comment by amirnapoletano** [comment]
Hey Chris, 

dankje, ik heb je feedback verwerkt;)
